# Generated by Django 3.2.7 on 2021-10-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211020_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='device',
        ),
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
